config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
  
  root "quiz#explanation"

  get '/login' => "sessions#new"
  post '/login' => 'sessions#create'
  get '/logout'=> 'sessions#destroy'
  
  get "quiz/friend_list"  => "quiz#friend_list"
  get "quiz/edit"  => "quiz#edit"
  get "quiz/quiz" => "quiz#quiz"
  get "quiz/show_answer" => "quiz#show_answer"
  get "quiz/input_answer" => "quiz#input_answer"
  get "quiz/show_ranking" => "quiz#show_ranking"
  get 'quiz/ajax_get_name_array' => 'quiz#ajax_get_name_array'
  get 'quiz/ajax_set_name_link' => 'quiz#ajax_set_name_link'
  get 'quiz/ajax_reset' => 'quiz#ajax_reset'
  get 'quiz/ajax_get_content' => 'quiz#ajax_get_content'

  post "quiz/ajax_profile_save" => "quiz#ajax_profile_save"
  post "quiz/ajax_content_save" => "quiz#ajax_content_save"
  post "quiz/ajax_post_answer" => "quiz#ajax_post_answer"
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
   protect_from_forgery
   before_action :logged_in_friend, except: [:ajax_post_answer, :ajax_profile_save, :ajax_content_save]
   
   def explanation
   end
   def friend_list
      @friends = Friend.joins(:content)
      @no_answer = params[:no_answer] if params[:no_answer].present? 
   end
   def edit
      if friend_is_present?
         @friend = Friend.find(params[:id])
      else
         @friend = Friend.new()
      end
      if content_is_present?
         @content = Content.find_by(friend_id: params[:id])
      else
         @content = Content.new()
      end
   end
   def quiz
      if friend_is_present? && content_is_present?
         @friends = [Friend.find_by(id: params[:id])]
         # 前回の対象のクイズを非出題対称にする
         preselected_contents = Content.where(selected_flag: true)
         preselected_contents.update(selected_flag: false)
         # 新しいクイズを出題対象にし、出題済みにする
         @content = Content.find_by(friend_id: params[:id])
         @content.update(selected_flag: true, done_flag: true)
      else
         redirect_to quiz_friend_list_path
      end
   end
   def input_answer
      @content = Content.find_by(selected_flag: true)
      friend_id = @content.friend_id
      @friends = Friend.all
      @friend = @friends.find_by(id: friend_id)
      @answer = Answer.new
   end
   def show_answer
      if content_is_present?
         answer = Content.find_by(friend_id: params[:id]).answer
         if params[:answer] == answer
            @result = "正解!"
         else
            @result = "残念！"
            @answer = answer.upcase
         end
      else
         redirect_to quiz_friend_list_path
      end
   end
   def show_ranking
      if Answer.all.blank?
         redirect_to quiz_friend_list_path no_answer: true
         return
      end
      # 正解数を集計
      results = Answer
      .joins(:friend)
      .group(:friend_id)
      .select('answers.friend_id, sum(answers.result) as sum, friends.full_name')
      .order(sum: "desc")
      # 3位までをまとめる
      @ranking_array = [{}, {}, {}]
      ranking = 0
      score = results.first.sum
      results.each do |result|
         if result.sum != score
            ranking += 1 
            score = result.sum
         end
         break if ranking > 2
         if @ranking_array[ranking]["#{result.sum.to_i}"]
            @ranking_array[ranking]["#{result.sum.to_i}"] += ", #{result.friend.full_name}さん"
         else
            @ranking_array[ranking]["#{result.sum.to_i}"] = "#{result.friend.full_name}さん"
         end
      end
   end
   def ajax_get_name_array
      names = Friend.joins(:content).where(contents: {done_flag: false}).pluck(:full_name)
      render json: names
   end
   def ajax_set_name_link
      friends = Friend.joins(:content).where(contents: {done_flag: false})
      selected_friend = friends.order("RAND()").first
      render json: selected_friend
   end
   def ajax_reset
      Answer.delete_all
      Content.update_all(selected_flag: false, done_flag: false)
   end
   def ajax_get_content
      hash = {}
      content = Content.find_by(selected_flag: true)
      hash[:friend_name] = Friend.find_by(id: content.friend_id).full_name
      hash[:content] = content
      render json: hash.to_json
   end
   def ajax_profile_save
      friend = Friend.find_by(id: params[:id].to_i)
      hash = {}
      if profile_params[:last_name].strip != "" && profile_params[:first_name].strip != ""
         if friend
            friend.update(profile_params)
            friend.update(password_digest: ("guest" + friend.id.to_s).crypt("secure_key"))
            hash[:friend_id] = params[:id].to_i
         else
            Friend.create(profile_params)
            friend = Friend.last(1)[0]
            friend.update(password_digest: ("guest" + friend.id.to_s).crypt("secure_key"))
            hash[:friend_id] = Friend.last(1).first.id
         end
         hash[:msg] = "保存しました！"
         hash[:state] = "done"
         render json: hash.to_json
      else
         hash[:msg] = "名前を入力してください！"
         hash[:state] = "fail"
         render json: hash.to_json 
      end
   end
   def ajax_content_save
      content = Content.find_by(friend_id: params[:friend_id].to_i)
      hash = {}
      # postされる全てのパラメータが入力されているときのみ保存
      if content_params.values.reject(&:empty?).length == 8
         if content
            content.update(content_params)
         else
            Content.create(content_params)
         end
         hash[:msg] = "保存しました！"
         hash[:state] = "done"
         render json: hash.to_json
      elsif content_params[:friend_id].blank?
         pp "プロフィール未作成"
         hash[:msg] = "先にプロフィールを作成してください！"
         hash[:state] = "fail"
         render json: hash.to_json 
      else
         hash[:msg] = "全ての項目を入力してください！"
         hash[:state] = "fail"
         render json: hash.to_json 
      end
   end
   def ajax_post_answer
      answer = Content.find_by(id: params[:content_id]).answer
      result_record = Answer.where(friend_id: params[:answerer_id], content_id: params[:content_id])
      if params[:ans] == answer
         if result_record.present?
            result_record.update(result: 1)
         else
            Answer.create(friend_id: params[:answerer_id], content_id: params[:content_id], result: 1)
         end
      else
         if result_record.present?
            result_record.update(result: 0)
         else
            Answer.create(friend_id: params[:answerer_id], content_id: params[:content_id], result: 0)
         end
      end   
      hash = {}
      hash[:msg] = "名前を入力してください！"
      hash[:state] = "fail"
      render json: hash.to_json
   end
   
   private
   def profile_params
      params[:full_name] = params[:last_name] + params[:first_name]
      params.permit(:id, :group, :last_name_en, :first_name_en, :full_name, :last_name, :first_name, :caption, :job, :password_digest, :image)
   end
   def content_params
      params.permit(:friend_id, :intro, :question, :option_a, :option_b, :option_c, :option_d, :answer)
   end
   def friend_is_present?
      params[:id].present? && Friend.find_by(id: params[:id])
   end
   def content_is_present?
      params[:id].present? && Content.find_by(friend_id: params[:id])
   end
end

app/views/quiz/_footer.html.erb
<div class="footer-wrapper">
    <div class="button-wrapper">
        <% if params == 'exp' %>
            <div class="back-wrapper">
                <span class="material-icons-outlined js-target-back">arrow_back</span>
            </div>
            <div class="forward-wrapper">
                <%= link_to quiz_friend_list_path, class: "list-link-first" do %>   
                    <span class="material-icons-outlined js-target-forward">arrow_forward</span>
                <% end %>
            </div>
        <% elsif params == 'quiz' %>
            <div class="quiz-forward-wrapper">
                <%= link_to quiz_show_answer_path(id: @friends[0].id), class: "answer-link js-target-answer-link u-hide" do %> 
                    <span class="answer-check">Answer Check</span>  
                    <span class="material-icons-outlined  arrorw-forward js-target-forward">arrow_forward</span>
                <% end %>
                <span class="pre-select-answer js-target-pre-select-answer">Please Select Answer</span>
            </div>
        <% elsif params == 'show_answer' %>
            <div class="show-answer-forward-wrapper">
                <%= link_to quiz_friend_list_path, class: "list-link-second js-target-list-link-socond" do %> 
                    <span class="go-to-list">Go To List</span>  
                    <span class="material-icons-outlined js-target-forward">arrow_forward</span>
                <% end %>
            </div>
        <% end %>
    </div>
</div>

<script>
$(function(){
    // 関数定義
    let isShow = (selector) => {return !selector.hasClass('u-hide')};
    // 変数定義
    let greeting = $('.js-target-greeting');
    let procedure = $('.js-target-procedure');
    let start = $('.js-target-start');
    // 実行 
    $('.js-target-forward').on('click', () => {
        if (isShow(greeting)) {
            greeting.addClass('u-hide');
            procedure.removeClass('u-hide');
            return false
        } else if (isShow(procedure)) {
            procedure.addClass('u-hide');
            start.removeClass('u-hide');
            return false
        } else if (isShow(start)) {
            console.log("no more to go next")
        }
    });
    $('.js-target-back').on('click', () => {
        if (isShow(greeting)) {
            console.log("no more to go back")
        } else if (isShow(procedure)) {
            procedure.addClass('u-hide');
            greeting.removeClass('u-hide');
        } else if (isShow(start)) {
            start.addClass('u-hide');
            procedure.removeClass('u-hide');
        }
    });
});
</script>

app/views/quiz/_friend_card.html.erb
<% @friends.each do |f| %>
    <div class="person-wrapper" id=<%= f.full_name %> >
        <div class="image-wrapper">
            <% if f.image.attached? %>
                <%= image_tag f.image %>
            <% else %>
                <span class="material-icons-outlined">
                    account_circle
                </span>
            <% end %>
        </div>
        <% if params != "quiz" %>
            <%= link_to quiz_edit_path(id: f.id) do %>
                <div class="edit-button-wrapper">
                    <span class="material-icons">edit</span>
                </div>
            <% end %>
        <% end %>
        <div class="text-wrapper">
            <p class="group"><%= f.group %></p>
            <div class="name-wrapper">
                <div class="name-en">
                    <p class="last-name-en"><%= f.last_name_en %></p>
                    <p class="first-name-en"><%= f.first_name_en %></p>
                </div>
                <div class="name-jp">
                    <p class="last-name-jp"><%= f.last_name %></p>
                    <p class="first-name-jp"><%= f.first_name %></p>
                </div>
            </div>
            <p class="caption"><%= f.caption %></p>
            <p class="job"><%= f.job %></p>
            <% if params != 'quiz' %>
                <%= link_to quiz_quiz_path(id: f.id) do%>
                    <div class="button-wrapper">
                        <span class="button-text">GO TO QUIZ</span> 
                    </div>
                <% end %>
            <% end %>
        </div>
    </div>
<% end %>
<script>
$('.edit-button-wrapper').on('click', () => {
    let result = window.confirm('管理者専用：クイズを編集しますか？');
    if (!result) { return false }
});
</script>

app/views/quiz/_header.html.erb
<div class="header-wrapper">
    <%= link_to root_path, class: "logo-link" do %>
        <div class="logo-wrapper">
            <span>Friend Quiz</span>
        </div>
    <% end %>
    <div class="header-button-wrapper">
        <%= link_to quiz_input_answer_path do %>
            <div class="input-answer-button-wrapper">
                <span class="material-icons-outlined">quiz</span>
            </div>
        <% end %>
        <%= link_to quiz_friend_list_path do %>
            <div class="frined-list-button-wrapper">
                <span class="material-icons-outlined">people</span>
            </div>
        <% end %>
        <%= link_to quiz_edit_path do %>
            <div class="friend-add-button-wrapper">
                <span class="material-icons-outlined">person_add</span>
            </div>
        <% end %>
    </div>
    <div class="login-info-wrapper">
        <span class="logged-in-name"><%= current_friend.full_name %>さん</span>
        <%= link_to logout_path do %>
            <span class="material-icons-outlined logout">logout</span>
        <% end %>
    </div>
</div>
<script>
$('.logout').on('click', () => {
    let result = window.confirm('ログアウトしますか？');
    if (!result) { return false }
});
$('.friend-add-button-wrapper').on('click', () => {
    let result = window.confirm('管理者専用：友達を追加しますか？');
    if (!result) { return false }
});
</script>

app/views/quiz/edit.html.erb
<div class="edit-profile-wrapper">
    <%= form_with id: :profile do |f| %>
        <%= f.label :image do %>
            <div class="image-wrapper">
                <%= f.file_field :image %>
                <% if @friend.image.attached? %>
                    <%= image_tag @friend.image, class: "attached_image" %>
                <% else %>
                    <span class="material-icons-outlined add-a-photo">add_a_photo</span>
                <% end %>
                <%# preview用の空のimgタグ %>
                <img id="preview" class="u-hide">
            </div>
        <% end %>
        <div class="text-wrapper">
            <p class="group"><%= f.select :group, group_select, { prompt: "選択してください", selected: @friend.group} %></p>
            <div class="name-wrapper">
                <div class="name-en">
                    <p class="last-name-en">
                        <%= f.text_field :last_name_en, value: @friend.last_name_en, :placeholder => "Sei" %>
                    </p>
                    <p class="first-name-en">
                        <%= f.text_field :first_name_en, value: @friend.first_name_en, :placeholder => "Mei" %>
                    </p>
                </div>
                <div class="name-jp">
                    <p class="last-name-jp">
                        <%= f.text_field :last_name, value: @friend.last_name, :placeholder => "姓" %>
                    </p>
                    <p class="first-name-jp">
                        <%= f.text_field :first_name, value: @friend.first_name, :placeholder => "名" %>
                    </p>
                </div>
            </div>
            <p class="caption">
                <%= f.text_area :caption, value: @friend.caption, :placeholder => "キャプション" %>
            </p>
            <p class="job">
                <%= f.text_field :job, value: @friend.job, :placeholder => "職業" %>
            </p>
        </div>
        <div class="profile-save-button-wrapper js-target-profile-save-button">
            <p class="button-text js-target-profile-button-text">SAVE</p> 
        </div>
        <%= f.hidden_field :id, value: @friend.id %>
    <% end %>
</div>

<div class="edit-content-wrapper">
    <%= form_with id: :content do |f| %>
        <p class="intro">
            <%= f.text_area :intro, value: @content.intro, :placeholder => "問題説明（。で改行されて表示）" %>
        </p>
        <p class="question">
            <%= f.text_field :question, value: @content.question, :placeholder => "問題提示（30文字まで：？で終わる一文で入力すること）" %>
        </p>
        <p class="option">
            A:<%= f.text_field :option_a, value: @content.option_a %>
            B:<%= f.text_field :option_b, value: @content.option_b %>
            <br>
            C:<%= f.text_field :option_c, value: @content.option_c %>
            D:<%= f.text_field :option_d, value: @content.option_d %>
        </p>
        <p class="answer">
            答え:<%= f.select :answer, answer_select, { prompt: "選択してください", selected: @content.answer} %>
        </p>
        <div class="content-save-button-wrapper js-target-content-save-button">
            <p class="button-text js-target-content-button-text">SAVE</p> 
        </div>
        <%= f.hidden_field :friend_id, value: @friend.id %>
    <% end %>
</div>


<script>
$(function(){
    // プロフィールフォーム送信
    $('.js-target-profile-save-button').on('click', () => {        
        let form = new FormData(document.getElementById("profile"));
        $.ajax({
            type: 'POST', 
            url: '/quiz/ajax_profile_save', 
            data: form, 
            dataType: 'json',
            // 画像データの送信に必要な設定
            contentType: false,
            processData: false
        })
        .done(function (res) {
            console.log("ajax成功");
            if (res.state == "done") {
                $('#friend_id').val(res.friend_id);
                $('.js-target-profile-button-text').text(`${res.msg}`);
                setTimeout(function(){$('.js-target-profile-button-text').text("SAVE");}, 2000);
            } else {
                alert(`${res.msg}`); 
            }
        })
        .fail(function() {
            console.log("ajax中断");
            alert("通信エラーが発生しました"); 
        })  
    });
    // クイズコンテンツフォーム送信
    $('.js-target-content-save-button').on('click', () => {        
        let form = new FormData(document.getElementById("content"));
        console.log(form)
        $.ajax({
            type: 'POST', 
            url: '/quiz/ajax_content_save', 
            data: form, 
            dataType: 'json',
            contentType: false,
            processData: false
        })
        .done(function (res) {
            console.log("ajax成功");
            if (res.state == "done") {
                $('.js-target-content-button-text').text(`${res.msg}`);
                setTimeout(function(){$('.js-target-content-button-text').text("SAVE");}, 2000);
            } else {
                alert(`${res.msg}`); 
            }
        })
        .fail(function() {
            console.log("ajax中断");
            alert("通信エラーが発生しました"); 
        })  
    });
    // プロフィール画像プレビュー
    $('#image').on('change', (e) => {
        $('.attached_image').addClass('u-hide');
        let reader = new FileReader();
        reader.onload = function (e) {
            $("#preview").attr('src', e.target.result);
            $("#preview").removeClass('u-hide');
            $(".add-a-photo").addClass('u-hide');
        }
        reader.readAsDataURL(e.target.files[0]);
    });
});
</script>

app/views/quiz/explanation.html.erb
<div class="exp-wrapper">
    <div class="text-wrapper">
        <span class="greeting js-target-greeting"><%= greeting_msg %></span>
        <span class="procedure js-target-procedure u-hide"><%= procedure_msg %></span>
        <span class="start js-target-start u-hide"><%= start_msg %></span>
    </div>
</div>
<%# スマホ対応 %>
<div class="cp-exp-wrapper">
    <div class="text-wrapper">
        <span class="greeting js-target-greeting"><%= greeting_msg %></span>
        <span class="procedure js-target-procedure u-hide"><%= procedure_msg %></span>
        <span class="start js-target-start u-hide"><%= start_msg %></span>
    </div>
</div>
<%= render partial: 'footer', locals: {params: 'exp'} %>

app/views/quiz/friend_list.html.erb
<div class="all-wrapper">
    <div class="side-wrapper">
        <div class="random-wrapper">
            <div class="random-text-wrapper">
                <p class="quiz-number">次の問題は、、</p>
                <p class="quiz-name js-target-quiz-name">???</p>
                <p class="quiz-name u-hide js-target-quiz-name-final"></p>
                <p class="keisyou">さん</p>
            </div>
            <div class="random-button-wrapper">
                <div class="shuffle-button js-target-shuffle-button"><span>SHUFFLE</span></div>
                <a class="name-link" href="">
                    <div class="go-button"><span>GO</span></div>
                </a>
            </div>
        </div>
        <div class="ranking-link-wrapper">
            <%= link_to quiz_show_ranking_path do %>
                <span class="ranking-link">! 結果発表 !</span>
            <% end %>
        </div>
        <div class="quiz-reset-wrapper">
            <span class="reset-button">! 結果をリセット !</span>
        </div>
    </div>
    <div class="list-wrapper">
        <%= render partial: 'friend_card' %>
    </div>
</div>
<script>
$(function(){
    // 関数定義
    let fade = () => {
        setInterval(function(){
            $('.js-target-quiz-name').fadeOut(50,function(){$(this).fadeIn(500)});
        }, 100);
    }
    let shuffle = (array) => {
        let m = array.length, t, i;
        while (m) {
            i = Math.floor(Math.random() * m--);
            t = array[m];
            array[m] = array[i];
            array[i] = t;
        }
        $('.js-target-quiz-name').text(array[0]);
    }
    let switch_name = (array) => {
        setInterval(function(){
            shuffle(array);
        }, 500);
    }
    let ajax_get_name_array = () => {
        // 未出題の名前配列を取得し、名前切り替え
        $.ajax({
            type: 'GET', 
            url: '/quiz/ajax_get_name_array', 
            dataType: 'json'
        })
        .done(function (res) {
            if (res.length) {
                fade();
                direction.text('STOP');
                $('.js-target-quiz-name-final').addClass('u-hide')
                $('.js-target-quiz-name').removeClass('u-hide')
                switch_name(res);
            } else {
                alert("全てのクイズが終了しました！");
            }
        })
        .fail(function() {
            alert("通信エラーが発生しました"); 
        })
    }
    let ajax_set_name_link = () => {
        // GOのリンク先の変更
        $.ajax({
            type: 'GET', 
            url: '/quiz/ajax_set_name_link', 
            dataType: 'json'
        })
        .done(function (res) {
            selected_name = res.full_name
            console.log(selected_name);
            $('.js-target-quiz-name-final').text(selected_name);
            $('.js-target-quiz-name-final').removeClass('u-hide')
            $('.js-target-quiz-name').addClass('u-hide')
            $(".name-link").attr("href", `#${selected_name}`)
        })
        .fail(function() {
            alert("通信エラーが発生しました"); 
        })
    }
    let ajax_reset = () => {
        // クイズ結果のリセット
        $.ajax({
            type: 'GET', 
            url: '/quiz/ajax_reset', 
            dataType: 'json'
        })
        .done(function (res) {

            alert("リセットしました"); 
        })
        .fail(function() {
            alert("通信エラーが発生しました"); 
        })
    }
    // 変数定義
    let names = '';
    let direction = $('.js-target-shuffle-button').find('span');
    let finalName = '';
    // 実行
    if ('<%= @no_answer %>') {alert('まだ回答がありません')}
    $('.shuffle-button').on('click', () => {
        if (direction.text() == 'SHUFFLE') {
            // SHUFFLEをクリックで名前切り替え
            ajax_get_name_array();
        } else {
            // STOPをクリックで名前設定、GOのリンク先を変更
            direction.text('SHUFFLE');
            ajax_set_name_link();
        }
    });
    $('.reset-button').on('click', () => {
        if (confirm('リセットしますか？')) {
            ajax_reset();
        } else {
            return false
        }
    });
});
</script>

app/views/quiz/input_answer.html.erb
<div class="pre-option-wrapper">
    <span class="pre-name">現在の問題は</span>
    <span class="content-name"><%= @friend.full_name %><br></span>
    <span class="after-name">さん</span>
</div>
<div class="pre-option-wrapper">
    <span class="pre-name">あなた(回答者)は</span>
    <span class="answerer-name">
        <select class="name-select js-target-name-select">
            <%= name_select %>  
        </select>
    <span class="material-icons-outlined arrow_drop_down">arrow_drop_down</span>
    </span>
    <span class="after-name">さん</span>
</div>
<%= form_with do |f| %>
    <%# PC用 %>
    <table class="option-wrapper">
        <tr>
            <td class="js-target-a not-selected">A: <%= @content.option_a %></td>
            <td class="js-target-b not-selected">B: <%= @content.option_b %></td>
        </tr>
        <tr>
            <td class="js-target-c not-selected">C: <%= @content.option_c %></td>
            <td class="js-target-d not-selected">D: <%= @content.option_d %></td>
        </tr>
    </table>
    <%# スマホ用 %>
    <table class="cp-option-wrapper">
        <tr>
            <td class="js-target-a not-selected">A: <%= @content.option_a %></td>
        </tr>
        <tr>
            <td class="js-target-b not-selected">B: <%= @content.option_b %></td>
        </tr>
        <tr>
            <td class="js-target-c not-selected">C: <%= @content.option_c %></td>
        </tr>
        <tr>
            <td class="js-target-d not-selected">D: <%= @content.option_d %></td>
        </tr>
    </table>
    <div class="post-button js-target-post-button">
        <span>送信する</span>
    </div>
<% end %>
<script>
$(function() {
    // 関数定義
    let selectAnswer = (element, answer) => {
        $('td').removeClass('selected');
        $('td').addClass('not-selected');
        element.removeClass('not-selected');
        element.addClass('selected');
        ans.ans = answer;
    }
    let updateContent = (name, content) => {
        $('.content-name').text(name);
        $('.js-target-a').text(content.option_a);
        $('.js-target-b').text(content.option_b);
        $('.js-target-c').text(content.option_c);
        $('.js-target-d').text(content.option_d);
    }
    // 回答者セット
    $('.name-select').val('<%= current_friend.id %>');
    // 回答用意
    let ans = { answerer_id: $('.name-select').val(),
                content_id: '<%= @content.id %>',
                ans: ""};
    // 問題対象者用意
    let contentName = $('.content-name').text();
    // 回答者取得
    $('.js-target-name-select').on('change', () => {ans.answerer_id = $('.name-select').val();}); 
    // 回答取得
    $('.js-target-a').click(function(){selectAnswer($(this), "a");});
    $('.js-target-b').click(function(){selectAnswer($(this), "b");});
    $('.js-target-c').click(function(){selectAnswer($(this), "c");});
    $('.js-target-d').click(function(){selectAnswer($(this), "d");});
    // 回答送信
    $('.js-target-post-button').on('click', () => { 
        if (ans.ans != '') {
            $.ajax({
                type: 'POST', 
            url: '/quiz/ajax_post_answer', 
            data: ans, 
            dataType: 'json'
            })
            .done(function (res) {
                console.log("ajax成功");
                alert("回答を送信しました"); 
            })
            .fail(function() {
                console.log("ajax中断");
                alert("通信エラーが発生しました"); 
            })  
        } else {
            alert('回答を選択してください');
        }
    });
    // 問題取得
    setInterval(function(){
        $.ajax({
            type: 'GET', 
            url: '/quiz/ajax_get_content', 
            dataType: 'json'
        })
        .done(function (res) {
            if (res.friend_name != contentName) {
                ans.content_id = res.content.id
                updateContent(res.friend_name, res.content);
                contentName = res.friend_name;
                alert("問題を開始します"); 
            }
        })
        .fail(function() {
            console.log("ajax中断");
            alert("通信エラーが発生しました"); 
        })
    }, 5000); 
});
</script>

app/views/quiz/show_answer.html.erb
<div class="result-msg-wrapper">
    <span class="result"><%= @result %></span>
    <% if @answer.present? %>
        <span class="after-msg">正解は<%= @answer %>でした。</span>
    <% else %>
        <div class="circle"></div>
        <span class="after-msg">ありがとうございます！</span>
    <% end %>
</div>
<%= render partial: 'footer', locals: {params: "show_answer"}%>

app/views/quiz/show_ranking.html.erb
<div class="ranking-wrapper">
    <table class="ranking-table">
        <tr>
            <td class="ranking ranking-1">第1位<td>
            <td class="names"><%= @ranking_array[0].values[0] %><td>
            <td class="score"><%= @ranking_array[0].keys[0] %>点<td>
        <tr>
        <tr>
            <td class="ranking ranking-2">第2位<td>
            <td class="names"><%= @ranking_array[1].values[0] %><td>
            <td class="score"><%= @ranking_array[1].keys[0] %>点<td>
        <tr>
        <tr>
            <td class="ranking ranking-3">第3位<td>
            <td class="names"><%= @ranking_array[2].values[0] %><td>
            <td class="score"><%= @ranking_array[2].keys[0] %>点<td>
        <tr>
    </table>
</div>
<%= render partial: 'footer', locals: {params: "show_answer"}%>